package com.example.digiwagen;

import java.util.ArrayList;
import java.util.List;

//Simplesmente para facilitar e organizar a criação da lista de carros
public class CarMockBuilder {
    public static List<CarListItem> build() {
        List<CarListItem> carListItems = new ArrayList<>();

        carListItems.add(new CarListItem(R.drawable.carro_lamborgini, "Lamborgini A32", "Prepare-se para experimentar o ápice do luxo e da velocidade com o Lamborghini A32! Este carro é mais do que apenas um veículo - é uma máquina de sonhos sobre rodas. Com sua carroceria aerodinâmica e linhas elegantes, o A32 não apenas corta o ar, mas domina cada centímetro do asfalto.\n\nMas o que realmente faz o coração de qualquer entusiasta de carros bater mais rápido é o motor V12 sob o capô. Com uma potência que desafia a gravidade, o A32 pode acelerar de 0 a 100 km/h em questão de segundos. É como ter seu próprio foguete pessoal na estrada!\n\nAlém da pura potência, o interior do Lamborghini A32 é uma obra-prima de luxo e tecnologia. Os assentos esculpidos abraçam você com conforto enquanto você desfruta do som celestial do sistema de áudio premium. E com recursos de conectividade de última geração, você pode manter-se conectado e no controle, onde quer que vá.", 230.50));
        carListItems.add(new CarListItem(R.drawable.carro_jipe, "Jipe S20", "Quer se aventurar fora do comum? O Jipe S20 é o parceiro perfeito para suas expedições fora de estrada! Construído para enfrentar qualquer terreno, este veículo robusto combina potência e versatilidade em um pacote imbatível.\n\nCom um motor turbocharged que ruge com força, o S20 pode enfrentar desde trilhas enlameadas até estradas desertas sem perder o fôlego. Sua suspensão reforçada e tração nas quatro rodas garantem que você possa superar qualquer obstáculo com confiança e estilo.\n\nMas não se engane - o Jipe S20 não sacrifica o conforto pelo desempenho. Seu interior espaçoso e ergonomicamente projetado oferece todo o conforto que você precisa, mesmo nas viagens mais longas. E com recursos de entretenimento e conectividade de última geração, você nunca estará entediado, mesmo nos lugares mais remotos.", 10.50));
        carListItems.add(new CarListItem(R.drawable.carro_coupe, "Coupet Special Lorenzetti", "Entre no mundo da elegância e do desempenho com o Coupet Special Lorenzetti! Este carro esportivo é uma combinação perfeita de estilo, velocidade e luxo. Com um design aerodinâmico e curvas impressionantes, o Lorenzetti é uma obra de arte em movimento.\n\nSob o capô, você encontrará um motor de alto desempenho que proporciona uma aceleração suave e poderosa. Cada curva e cada reta são uma oportunidade para experimentar a emoção pura da velocidade. E com sua suspensão ajustável, você pode personalizar sua experiência de condução para se adequar ao seu estilo.\n\nMas o Coupet Special Lorenzetti não é apenas sobre desempenho - seu interior é um santuário de luxo e conforto. Os assentos de couro macio abraçam você enquanto você se envolve com o sistema de entretenimento de última geração. E com tecnologia de ponta em cada detalhe, você está sempre no controle da sua jornada.", 10000.10));
        carListItems.add(new CarListItem(R.drawable.carro_audi_suv, "Audi SUV-X", "Eleve seu estilo de vida com o Audi SUV-X! Este SUV de luxo combina elegância, desempenho e versatilidade para uma experiência de condução incomparável. Com um design exterior impressionante e uma cabine espaçosa, o SUV-X é projetado para impressionar em todos os sentidos.\n\nSob o capô, você encontrará um motor potente que oferece uma combinação perfeita de eficiência e desempenho. Com sua tração nas quatro rodas e suspensão adaptativa, o SUV-X oferece uma condução suave e ágil, seja na estrada ou fora dela.\n\nMas o Audi SUV-X não é apenas sobre desempenho - seu interior luxuoso redefine o conforto e a comodidade. Os assentos ergonômicos e o acabamento em couro de alta qualidade garantem que cada viagem seja uma experiência de primeira classe. E com tecnologia de ponta em cada detalhe, você está sempre conectado e no controle.", 730.50));
        carListItems.add(new CarListItem(R.drawable.carro_mercedes_sport, "Mercedes Fly-Sport", "Experimente o luxo e o desempenho de classe mundial com o Mercedes Fly-Sport! Este carro esportivo é a combinação perfeita de elegância e potência, projetado para oferecer uma experiência de condução que vai além das suas expectativas. Com um design aerodinâmico e linhas elegantes, o Fly-Sport não apenas chama a atenção, mas também oferece um desempenho excepcional em cada curva.\n\nSob o capô, você encontrará um motor poderoso que oferece uma aceleração rápida e uma resposta ágil. Seja na pista ou na estrada, o Fly-Sport oferece uma experiência de condução emocionante que vai deixar você querendo mais. E com sua suspensão ajustável e tecnologia de ponta, você pode personalizar sua experiência de condução para se adequar ao seu estilo.\n\nMas o Mercedes Fly-Sport não é apenas sobre desempenho - seu interior luxuoso redefine o conforto e a conveniência. Os assentos de couro premium abraçam você enquanto você desfruta dos mais recentes avanços em tecnologia automotiva. E com recursos avançados de segurança, você pode ter tranquilidade em cada viagem.", 8720.10));
        carListItems.add(new CarListItem(R.drawable.carro_audi_rio, "Audi Rio Edition", "Faça uma declaração audaciosa com o Audi Rio Edition! Este carro esportivo combina um design arrojado com um desempenho excepcional para uma experiência de condução que é verdadeiramente emocionante. Com um motor potente e ágil, o Rio Edition oferece uma aceleração rápida e uma resposta ágil em cada curva.\n\nMas o Audi Rio Edition não é apenas sobre desempenho - seu interior luxuoso redefine o conforto e a conveniência. Os assentos espaçosos e ergonomicamente projetados oferecem suporte máximo durante longas viagens, enquanto os recursos avançados de conectividade mantêm você conectado em todos os momentos. Além disso, sua tecnologia de ponta e sistemas de segurança avançados garantem uma condução segura e tranquila em todas as suas aventuras.", 700.00));

        return carListItems;
    }
}
